title: Getting started with the Sense HAT
hero_image: images/banner.png
description: Explore the Sense HAT sensor board and its Python library
original_url: https://raspberrypi.org/learning/getting-started-with-the-sense-hat
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: 
technologies: physical computing, python
steps:
- title: Introduction
- title: What you will need
- title: What is a Sense HAT?
- title: Displaying text
- title: Displaying a single character
- title: Displaying images
- title: Setting orientation
- title: Sensing the environment
- title: Detecting movement
- title: Using the joystick
- title: "Challenge: putting it all together"
- title: "Challenge: more ideas"
