title: Getting started with the Sense HAT
hero_image: images/banner.png
description: Explore the Sense HAT sensor board and its Python library
original_url: https://raspberrypi.org/learning/getting-started-with-the-sense-hat
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: raspberry-pi, electronic-components, python, sense-hat
hardware: raspberry-pi, electronic-components, sense-hat
software: python
site_areas: projects
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: What is a Sense HAT?
- title: Displaying text
- title: Displaying a single character
- title: Displaying images
- title: Setting orientation
- title: Sensing the environment
- title: Detecting movement
- title: Using the joystick
- title: "Challenge: putting it all together"
- title: "Challenge: more ideas"